### ISSUE TITLE
是否考虑在 js 文件中支持便捷访问 state 中的数据呢? 

### ISSUE THREAD

**Issue by qiqingfu** [985563349/atomu#1]
遇到的场景，比如将商家和门店数据存储到 store 的 state 中，在请求拦截器需要获取某个 store 的 state 存储的数据，没有很好的方式，内部只对外暴漏了 bind、dispatch 和 订阅。

atomu 目前支持最好的场景是结合 Page 和 Component 使用。

**Comment by qiqingfu** [comment]
希望可以再对外暴漏一个 get 方法获取当前 store 的 state 状态。

**Comment by 985563349** [comment]
> 希望可以再对外暴漏一个 get 方法获取当前 store 的 state 状态。

近期将会添加。
